/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    blogContent: BlogContent;
    blogMarkdown: BlogMarkdown;
    code: Code;
  };
  collections: {
    media: Media;
    posts: Post;
    categories: Category;
    users: User;
    redirects: Redirect;
    "payload-kv": PayloadKv;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      posts: "posts";
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>;
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  locale: null;
  user: User & {
    collection: "users";
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogContent".
 */
export interface BlogContent {
  blockName?: string | null;
  blockType: "blogContent";
  blogContentFields: {
    richText: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ("ltr" | "rtl") | null;
        format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  id?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogMarkdown".
 */
export interface BlogMarkdown {
  blockName?: string | null;
  blockType: "blogMarkdown";
  blogMarkdownFields: {
    markdown: string;
  };
  id?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "code".
 */
export interface Code {
  blockName?: string | null;
  blockType: "code";
  codeFields: {
    language?: ("none" | "js" | "ts") | null;
    code: string;
    codeBlips?:
      | {
          row: number;
          label: string;
          feature: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ("ltr" | "rtl") | null;
              format:
                | "left"
                | "start"
                | "center"
                | "right"
                | "end"
                | "justify"
                | "";
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          enableLink?: boolean | null;
          link?: {
            type?: ("reference" | "custom") | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: "posts";
              value: number | Post;
            } | null;
            url?: string | null;
            label: string;
            customId?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  id?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  _status?: ("draft" | "published") | null;
  authors?: (number | User)[] | null;
  authorType?: ("guest" | "team") | null;
  category: number | Category;
  content: (BlogContent | Code)[];
  createdAt: string;
  dynamicThumbnail?: boolean | null;
  excerpt: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredMedia?: ("upload" | "videoUrl") | null;
  guestAuthor?: string | null;
  guestSocials?: {
    youtube?: string | null;
    twitter?: string | null;
    linkedin?: string | null;
    website?: string | null;
  };
  id: number;
  image?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedOn: string;
  relatedPosts?: (number | Post)[] | null;
  slug?: string | null;
  tags?: string[] | null;
  thumbnail?: (number | null) | Media;
  title: string;
  updatedAt: string;
  videoUrl?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  alt: string;
  createdAt: string;
  /**
   * Choose an upload to render if the visitor is using dark mode.
   */
  darkModeFallback?: (number | null) | Media;
  filename?: string | null;
  filesize?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  height?: number | null;
  id: number;
  mimeType?: string | null;
  thumbnailURL?: string | null;
  updatedAt: string;
  url?: string | null;
  width?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  createdAt: string;
  description: string;
  headline: string;
  id: number;
  name: string;
  posts?: {
    docs?: (number | Post)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  slug: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  createdAt: string;
  email: string;
  firstName: string;
  hash?: string | null;
  id: number;
  lastName: string;
  lockUntil?: string | null;
  loginAttempts?: number | null;
  password?: string | null;
  photo?: (number | null) | Media;
  resetPasswordExpiration?: string | null;
  resetPasswordToken?: string | null;
  roles: ("admin" | "public")[];
  salt?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  /**
   * Example: `payloadcms`
   */
  twitter?: string | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  createdAt: string;
  from: string;
  id: number;
  to?: {
    type?: ("reference" | "custom") | null;
    reference?: {
      relationTo: "posts";
      value: number | Post;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id: number;
  key: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  createdAt: string;
  document?:
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "posts";
        value: number | Post;
      } | null)
    | ({
        relationTo: "categories";
        value: number | Category;
      } | null)
    | ({
        relationTo: "users";
        value: number | User;
      } | null)
    | ({
        relationTo: "redirects";
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  id: number;
  updatedAt: string;
  user: {
    relationTo: "users";
    value: number | User;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  createdAt: string;
  id: number;
  key?: string | null;
  updatedAt: string;
  user: {
    relationTo: "users";
    value: number | User;
  };
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  batch?: number | null;
  createdAt: string;
  id: number;
  name?: string | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  createdAt?: T;
  darkModeFallback?: T;
  filename?: T;
  filesize?: T;
  focalX?: T;
  focalY?: T;
  height?: T;
  mimeType?: T;
  thumbnailURL?: T;
  updatedAt?: T;
  url?: T;
  width?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  _status?: T;
  authors?: T;
  authorType?: T;
  category?: T;
  content?: T | {};
  createdAt?: T;
  dynamicThumbnail?: T;
  excerpt?: T;
  featuredMedia?: T;
  guestAuthor?: T;
  guestSocials?:
    | T
    | {
        youtube?: T;
        twitter?: T;
        linkedin?: T;
        website?: T;
      };
  image?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedOn?: T;
  relatedPosts?: T;
  slug?: T;
  tags?: T;
  thumbnail?: T;
  title?: T;
  updatedAt?: T;
  videoUrl?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  createdAt?: T;
  description?: T;
  headline?: T;
  name?: T;
  posts?: T;
  slug?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  createdAt?: T;
  email?: T;
  firstName?: T;
  hash?: T;
  lastName?: T;
  lockUntil?: T;
  loginAttempts?: T;
  photo?: T;
  resetPasswordExpiration?: T;
  resetPasswordToken?: T;
  roles?: T;
  salt?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
  twitter?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  createdAt?: T;
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  data?: T;
  key?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  createdAt?: T;
  document?: T;
  globalSlug?: T;
  updatedAt?: T;
  user?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  createdAt?: T;
  key?: T;
  updatedAt?: T;
  user?: T;
  value?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  batch?: T;
  createdAt?: T;
  name?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
