/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  ContractMethod,
  ContractRunner,
  FunctionFragment,
  Interface,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
} from "../../../common";

export interface AddressInterface extends Interface {}

export interface Address extends BaseContract {
  connect(runner?: ContractRunner | null): Address;

  filters: {};

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  interface: AddressInterface;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<TypedListener<TCEvent>[]>;
  listeners(eventName?: string): Promise<Listener[]>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent> | TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent> | TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent> | TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<TypedEventLog<TCEvent>[]>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;
  waitForDeployment(): Promise<this>;
}
