/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  AddressLike,
  BaseContract,
  BigNumberish,
  BytesLike,
  ContractMethod,
  ContractRunner,
  EventFragment,
  FunctionFragment,
  Interface,
  Listener,
  Result,
} from "ethers";
import type {
  TypedContractEvent,
  TypedContractMethod,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedLogDescription,
} from "../../common";

export interface WithdrawManagerInterface extends Interface {
  decodeFunctionResult(
    functionFragment:
      | "withdrawn(address,address)"
      | (
          | "withdrawn(address)"
          | ("totalWithdrawn()" | "totalWithdrawn(address)")
        ),
    data: BytesLike
  ): Result;
  encodeFunctionData(
    functionFragment: "totalWithdrawn()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawn(address)" | "totalWithdrawn(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawn(address,address)",
    values: [AddressLike, AddressLike]
  ): string;

  getEvent(
    nameOrSignatureOrTopic: "ERC20Withdrawal" | "Initialized" | "Withdrawal"
  ): EventFragment;
  getFunction(
    nameOrSignature:
      | "totalWithdrawn(address)"
      | "totalWithdrawn()"
      | "withdrawn(address)"
      | "withdrawn(address,address)"
  ): FunctionFragment;
}

export namespace ERC20WithdrawalEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    amount: bigint;
    to: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WithdrawManager extends BaseContract {
  connect(runner?: ContractRunner | null): WithdrawManager;

  filters: {
    "ERC20Withdrawal(address,address,uint256)": TypedContractEvent<
      ERC20WithdrawalEvent.InputTuple,
      ERC20WithdrawalEvent.OutputTuple,
      ERC20WithdrawalEvent.OutputObject
    >;
    ERC20Withdrawal: TypedContractEvent<
      ERC20WithdrawalEvent.InputTuple,
      ERC20WithdrawalEvent.OutputTuple,
      ERC20WithdrawalEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Withdrawal(address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };

  getEvent(
    key: "ERC20Withdrawal"
  ): TypedContractEvent<
    ERC20WithdrawalEvent.InputTuple,
    ERC20WithdrawalEvent.OutputTuple,
    ERC20WithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;
  getFunction(
    nameOrSignature: "totalWithdrawn()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawn(address)" | "totalWithdrawn(address)"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawn(address,address)"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "view"
  >;

  interface: WithdrawManagerInterface;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<TypedListener<TCEvent>[]>;
  listeners(eventName?: string): Promise<Listener[]>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent> | TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent> | TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent> | TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<TypedEventLog<TCEvent>[]>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "totalWithdrawn()": TypedContractMethod<[], [bigint], "view">;

  "totalWithdrawn(address)": TypedContractMethod<
    [token: AddressLike],
    [bigint],
    "view"
  >;
  waitForDeployment(): Promise<this>;

  "withdrawn(address,address)": TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "view"
  >;

  "withdrawn(address)": TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;
}
