/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  images: {
    domains: [
      'tokens.1inch.io',
      'assets.coingecko.com',
      'ethapi.openocean.finance',
      's2.coinmarketcap.com',
      'raw.githubusercontent.com',
      'ethereum-optimism.github.io',
      'cloudstorage.openocean.finance',
      'elk.finance',
      'etherscan.io',
      'storage.googleapis.com',
      'jpyc.jp',
      'cryption-network.s3.us-east-2.amazonaws.com',
      'i.imgur.com',
      'i.ibb.co',
      'api-live.stableonegroup.com',
      'bscscan.com',
      'api.rubic.exchange',
      'maticcpad.com',
      'polygonscan.com',
      'afksystem.finance',
      'ipfs.io',
      'cf-ipfs.com',
      'oropocket.com',
      'matic.ripae.finance',
      'bookie.farm',
      'playgooeys.com',
      'polygon.impermax.finance',
      'cryptologos.cc',
      'flowimage.flow.page',
      'www.dropbox.com',
      'app.fluidy.fi',
      'dinox.io',
      'maticpad.com',
      'drive.google.com',
      'omni.ai',
      'wallet-asset.matic.network',
      'www.ankr.com',
      'cloudflare-ipfs.com',
      'www.datocms-assets.com',
      'logos.covalenthq.com',
    ],
  },
};
