/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  AddressLike,
  BaseContract,
  BigNumberish,
  BytesLike,
  ContractMethod,
  ContractRunner,
  EventFragment,
  FunctionFragment,
  Interface,
  Listener,
  Result,
} from "ethers";
import type {
  TypedContractEvent,
  TypedContractMethod,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedLogDescription,
} from "../common";

export interface SplitFactoryInterface extends Interface {
  decodeFunctionResult(
    functionFragment:
      | "transferOwnership"
      | (
          | "renounceOwnership"
          | ("owner" | ("getAddress" | ("createSplit" | "beacon")))
        ),
    data: BytesLike
  ): Result;
  encodeFunctionData(
    functionFragment: "getAddress" | "createSplit",
    values: [AddressLike[], BigNumberish[], string, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership" | ("owner" | "beacon"),
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  getEvent(
    nameOrSignatureOrTopic: "CreateSplitProxy" | "OwnershipTransferred"
  ): EventFragment;
  getFunction(
    nameOrSignature:
      | "beacon"
      | "createSplit"
      | "getAddress"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;
}

export namespace CreateSplitProxyEvent {
  export type InputTuple = [proxy: AddressLike];
  export type OutputTuple = [proxy: string];
  export interface OutputObject {
    proxy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    newOwner: string;
    previousOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SplitFactory extends BaseContract {
  beacon: TypedContractMethod<[], [string], "view">;
  connect(runner?: ContractRunner | null): SplitFactory;

  createSplit: TypedContractMethod<
    [
      payees: AddressLike[],
      shares: BigNumberish[],
      uri: string,
      metadataEditable: boolean,
      salt: BigNumberish,
    ],
    [undefined],
    "nonpayable"
  >;

  filters: {
    "CreateSplitProxy(address)": TypedContractEvent<
      CreateSplitProxyEvent.InputTuple,
      CreateSplitProxyEvent.OutputTuple,
      CreateSplitProxyEvent.OutputObject
    >;
    CreateSplitProxy: TypedContractEvent<
      CreateSplitProxyEvent.InputTuple,
      CreateSplitProxyEvent.OutputTuple,
      CreateSplitProxyEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };

  getAddress: TypedContractMethod<
    [
      payees: AddressLike[],
      shares: BigNumberish[],
      uri: string,
      metadataEditable: boolean,
      _salt: BigNumberish,
    ],
    [string],
    "view"
  >;

  getEvent(
    key: "CreateSplitProxy"
  ): TypedContractEvent<
    CreateSplitProxyEvent.InputTuple,
    CreateSplitProxyEvent.OutputTuple,
    CreateSplitProxyEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;
  getFunction(
    nameOrSignature: "createSplit"
  ): TypedContractMethod<
    [
      payees: AddressLike[],
      shares: BigNumberish[],
      uri: string,
      metadataEditable: boolean,
      salt: BigNumberish,
    ],
    [undefined],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<
    [
      payees: AddressLike[],
      shares: BigNumberish[],
      uri: string,
      metadataEditable: boolean,
      _salt: BigNumberish,
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner" | "beacon"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [undefined], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [undefined], "nonpayable">;

  interface: SplitFactoryInterface;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<TypedListener<TCEvent>[]>;
  listeners(eventName?: string): Promise<Listener[]>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent> | TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent> | TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  owner: TypedContractMethod<[], [string], "view">;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent> | TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<TypedEventLog<TCEvent>[]>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  renounceOwnership: TypedContractMethod<[], [undefined], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [undefined],
    "nonpayable"
  >;
  waitForDeployment(): Promise<this>;
}
