version: 2.1

parameters:
  run-shared:
    type: boolean
    default: false
  run-landing:
    type: boolean
    default: false
  run-app:
    type: boolean
    default: false
  run-docs:
    type: boolean
    default: false
  run-contracts:
    type: boolean
    default: false

workflows:
  run-landing:
    jobs:
      - lint:
          name: "[landing] lint"
      - test:
          name: "[landing] test"
      - deploy: &base
          name: "[landing] deploy staging"
          vercel-project-id: $VERCEL_PROJECT_ID_LANDING
          vercel-org-id: $VERCEL_ORG_ID
          vercel-token: $VERCEL_TOKEN
          requires:
            - "[landing] lint"
            - "[landing] test"
          vercel-environment: preview
          filters:
            branches:
              ignore: /main/
      - deploy:
          <<: *base
          name: "[landing] deploy production"
          vercel-environment: production
          filters:
            branches:
              only: /main/
