version: 2.1

parameters:
  run-shared:
    type: boolean
    default: false
  run-landing:
    type: boolean
    default: false
  run-app:
    type: boolean
    default: false
  run-docs:
    type: boolean
    default: false
  run-contracts:
    type: boolean
    default: false

workflows:
  run-landing:
    jobs:
      - lint:
          name: "Lint Landing"
      - test:
          name: "Test Landing"
      - deploy: &base
          name: "Deploy Landing to Preview"
          vercel-project-id: $VERCEL_PROJECT_ID_LANDING
          vercel-org-id: $VERCEL_ORG_ID
          vercel-token: $VERCEL_TOKEN
          requires:
            - "Lint Landing"
            - "Test Landing"
          vercel-environment: preview
          filters:
            branches:
              ignore: /main/
      - deploy:
          <<: *base
          name: "Deploy Landing to Production"
          vercel-environment: production
          filters:
            branches:
              only: /main/
