/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SplitBase } from "./SplitBase";
export type { SplitReceiver } from "./SplitReceiver";
export type { SplitSender } from "./SplitSender";
