/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  AddressLike,
  BaseContract,
  BigNumberish,
  BytesLike,
  ContractMethod,
  ContractRunner,
  EventFragment,
  FunctionFragment,
  Interface,
  Listener,
  Result,
} from "ethers";
import type {
  TypedContractEvent,
  TypedContractMethod,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedLogDescription,
} from "../../common";

export interface SplitSenderInterface extends Interface {
  decodeFunctionResult(
    functionFragment:
      | "withdrawn(address,address)"
      | (
          | "withdrawn(address)"
          | (
              | "withdraw(address,address)"
              | (
                  | "withdraw(address)"
                  | (
                      | "totalWithdrawn()"
                      | (
                          | "totalWithdrawn(address)"
                          | (
                              | "totalShares"
                              | (
                                  | "shares"
                                  | (
                                      | "payeeCount"
                                      | (
                                          | "payee"
                                          | (
                                              | "getPending(address)"
                                              | (
                                                  | "getPending(address,address)"
                                                  | (
                                                      | "batchWithdraw(bool,address[],address)"
                                                      | "batchWithdraw(bool,address[])"
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        ),
    data: BytesLike
  ): Result;

  encodeFunctionData(
    functionFragment: "batchWithdraw(bool,address[])",
    values: [boolean, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchWithdraw(bool,address[],address)",
    values: [boolean, AddressLike[], AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "payee", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "totalWithdrawn()" | ("totalShares" | "payeeCount"),
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment:
      | "withdrawn(address)"
      | (
          | "withdraw(address)"
          | ("totalWithdrawn(address)" | ("shares" | "getPending(address)"))
        ),
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment:
      | "withdrawn(address,address)"
      | ("withdraw(address,address)" | "getPending(address,address)"),
    values: [AddressLike, AddressLike]
  ): string;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposit"
      | "ERC20Withdrawal"
      | "Initialized"
      | "PayeeAdded"
      | "Withdrawal"
  ): EventFragment;
  getFunction(
    nameOrSignature:
      | "batchWithdraw(bool,address[])"
      | "batchWithdraw(bool,address[],address)"
      | "getPending(address,address)"
      | "getPending(address)"
      | "payee"
      | "payeeCount"
      | "shares"
      | "totalShares"
      | "totalWithdrawn(address)"
      | "totalWithdrawn()"
      | "withdraw(address)"
      | "withdraw(address,address)"
      | "withdrawn(address)"
      | "withdrawn(address,address)"
  ): FunctionFragment;
}

export namespace DepositEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    amount: bigint;
    from: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ERC20WithdrawalEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    amount: bigint;
    to: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayeeAddedEvent {
  export type InputTuple = [account: AddressLike, shares: BigNumberish];
  export type OutputTuple = [account: string, shares: bigint];
  export interface OutputObject {
    account: string;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    amount: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SplitSender extends BaseContract {
  "batchWithdraw(bool,address[],address)": TypedContractMethod<
    [withdrawETH: boolean, tokens: AddressLike[], account: AddressLike],
    [undefined],
    "nonpayable"
  >;

  "batchWithdraw(bool,address[])": TypedContractMethod<
    [withdrawETH: boolean, tokens: AddressLike[]],
    [undefined],
    "nonpayable"
  >;
  connect(runner?: ContractRunner | null): SplitSender;

  filters: {
    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "ERC20Withdrawal(address,address,uint256)": TypedContractEvent<
      ERC20WithdrawalEvent.InputTuple,
      ERC20WithdrawalEvent.OutputTuple,
      ERC20WithdrawalEvent.OutputObject
    >;
    ERC20Withdrawal: TypedContractEvent<
      ERC20WithdrawalEvent.InputTuple,
      ERC20WithdrawalEvent.OutputTuple,
      ERC20WithdrawalEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "PayeeAdded(address,uint256)": TypedContractEvent<
      PayeeAddedEvent.InputTuple,
      PayeeAddedEvent.OutputTuple,
      PayeeAddedEvent.OutputObject
    >;
    PayeeAdded: TypedContractEvent<
      PayeeAddedEvent.InputTuple,
      PayeeAddedEvent.OutputTuple,
      PayeeAddedEvent.OutputObject
    >;

    "Withdrawal(address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };

  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "ERC20Withdrawal"
  ): TypedContractEvent<
    ERC20WithdrawalEvent.InputTuple,
    ERC20WithdrawalEvent.OutputTuple,
    ERC20WithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "PayeeAdded"
  ): TypedContractEvent<
    PayeeAddedEvent.InputTuple,
    PayeeAddedEvent.OutputTuple,
    PayeeAddedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchWithdraw(bool,address[])"
  ): TypedContractMethod<
    [withdrawETH: boolean, tokens: AddressLike[]],
    [undefined],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchWithdraw(bool,address[],address)"
  ): TypedContractMethod<
    [withdrawETH: boolean, tokens: AddressLike[], account: AddressLike],
    [undefined],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "payee"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalWithdrawn()" | ("totalShares" | "payeeCount")
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw(address)"
  ): TypedContractMethod<[account: AddressLike], [undefined], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw(address,address)"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [undefined],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature:
      | "withdrawn(address)"
      | ("totalWithdrawn(address)" | ("shares" | "getPending(address)"))
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature:
      | "withdrawn(address,address)"
      | "getPending(address,address)"
  ): TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "view"
  >;

  "getPending(address,address)": TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "view"
  >;

  "getPending(address)": TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  interface: SplitSenderInterface;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<TypedListener<TCEvent>[]>;
  listeners(eventName?: string): Promise<Listener[]>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent> | TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent> | TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  payee: TypedContractMethod<[index: BigNumberish], [string], "view">;

  payeeCount: TypedContractMethod<[], [bigint], "view">;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent> | TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<TypedEventLog<TCEvent>[]>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  shares: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  totalShares: TypedContractMethod<[], [bigint], "view">;

  "totalWithdrawn()": TypedContractMethod<[], [bigint], "view">;

  "totalWithdrawn(address)": TypedContractMethod<
    [token: AddressLike],
    [bigint],
    "view"
  >;
  waitForDeployment(): Promise<this>;

  "withdraw(address,address)": TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [undefined],
    "nonpayable"
  >;

  "withdraw(address)": TypedContractMethod<
    [account: AddressLike],
    [undefined],
    "nonpayable"
  >;

  "withdrawn(address,address)": TypedContractMethod<
    [token: AddressLike, account: AddressLike],
    [bigint],
    "view"
  >;

  "withdrawn(address)": TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;
}
