export const RECIPIENT_TYPE_KEY = {
  DEFAULT_RECIPIENT: "DEFAULT_RECIPIENT",
  DEFAULT_GROUP: "DEFAULT_GROUP",
  TIMED_GROUP: "TIMED_GROUP",
  PRIORITIZED_GROUP: "PRIORITIZED_GROUP",
} as const;

export const CALCULATION_TYPE_KEY = {
  FIXED: "FIXED",
  PERCENTAGE: "PERCENTAGE",
} as const;

export const RECIPIENT_TYPE_CONFIG = {
  [RECIPIENT_TYPE_KEY.DEFAULT_RECIPIENT]: {
    key: RECIPIENT_TYPE_KEY.DEFAULT_RECIPIENT,
    name: "Default Recipient",
  },
  [RECIPIENT_TYPE_KEY.DEFAULT_GROUP]: {
    key: RECIPIENT_TYPE_KEY.DEFAULT_GROUP,
    name: "Default Group",
  },
  [RECIPIENT_TYPE_KEY.TIMED_GROUP]: {
    key: RECIPIENT_TYPE_KEY.TIMED_GROUP,
    name: "Timed Group",
  },
  [RECIPIENT_TYPE_KEY.PRIORITIZED_GROUP]: {
    key: RECIPIENT_TYPE_KEY.PRIORITIZED_GROUP,
    name: "Prioritized Group",
  },
};

export const CALCULATION_TYPE_CONFIG = {
  [CALCULATION_TYPE_KEY.PERCENTAGE]: {
    key: CALCULATION_TYPE_KEY.PERCENTAGE,
    name: "Percentage",
  },
  [CALCULATION_TYPE_KEY.FIXED]: {
    key: CALCULATION_TYPE_KEY.FIXED,
    name: "Fixed",
  },
};
